package com.example.tulipsante.pulse.oximeter.repository.greendao;


import com.example.tulipsante.pulse.oximeter.repository.bean.SpoRecord;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig spoRecordDaoConfig;

    private final SpoRecordDao spoRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        spoRecordDaoConfig = daoConfigMap.get(SpoRecordDao.class).clone();
        spoRecordDaoConfig.initIdentityScope(type);

        spoRecordDao = new SpoRecordDao(spoRecordDaoConfig, this);

        registerDao(SpoRecord.class, spoRecordDao);
    }
    
    public void clear() {
        spoRecordDaoConfig.clearIdentityScope();
    }

    public SpoRecordDao getSpoRecordDao() {
        return spoRecordDao;
    }

}
